name: 'Create release'
description: 'Create a Release computing the changelog based on commits.'

inputs:
  artifacts:
    description: 'An optional set of paths representing artifacts to upload to the release. This may be a single path or a comma delimited list of paths (or globs). E.g., "release.tar.gz,foo/*.txt".'
    default: ''
    required: false
  token:
    description: 'Github token for deployment.'
    required: true
  version:
    description: 'The version that will be created.'
    required: true

runs:
  using: "composite"
  steps:
    - name: Build Changelog
      uses: danysk/compute-changelog-action@0.1.63
      with:
        token: ${{ inputs.token }}
    - uses: ncipollo/release-action@v1
      name: Create GitHub Release
      with:
        tag: ${{ inputs.version }}
        replacesArtifacts: true
        token: ${{ inputs.token }}
        bodyFile: CHANGELOG.md
        artifacts: ${{ inputs.artifacts }}
